### ISSUE TITLE
HashiCorp Vault Version Compatibility

### ISSUE THREAD

**Issue by GuruParin** [jonasvinther/medusa#55]
Remote vault server is running version 1.3.2.

When I tried to run - medusa export, it prompts an error:

Error: no keys found using path [secret/metadata//] on Vault instance [https://xxx]

Is there a minimum vault server version requirement? If so, better to mention in README

**Comment by jonasvinther** [comment]
Hi @GuruParin
That is actually a really good question. I will need to test this and look into the release notes to see if there is some breaking changes at some point. Let me look into this and get back to you.

**Comment by elulcao** [comment]
I discovered the same issue with Vault 0.11.2 and Medusa Commit 5bfef5b
just in case someone else faced the same issue.

**Comment by jonasvinther** [comment]
I also think that this issue is related to using the wrong kv engine. I just tested and Medusa seems to be working with Vault version 0.10.0 and newer. So that should not be the issue. 
Also @elulcao you should consider upgrading your Vault instance if you are running version 0.11.2, that version is more than 3 yers old :)
I will add the support  the minimum vault server version requirement as you mentioned @GuruParin.

**Comment by GuruParin** [comment]
Tested on 4 Vault instances with different version, all working fine when kv engine version is correctly set.

I did overlook the kv engine version :(

Thank you both.
