### ISSUE TITLE
Export Error '<' looking for beginning of value OR missing vaultaddr parameter

### ISSUE THREAD

**Issue by Yasinmohammed007** [jonasvinther/medusa#82]
**URL**: http://207.254.25.36:8000/secrets/kv/secret/
it has subfolders in it, but for testing i used this http://207.254.25.36:8000/secrets/kv/secret/android/dev/keys

**Cmd Executed**:
./medusa export secret/android/dev/ -k --address="http://207.254.25.36:8000/secrets/kv/secret/android/dev/"

./medusa export secret/android/dev/ -k --address="http://207.254.25.36:8000/secrets/kv/"

let me know if i am passing the urlFlag or VaultPath wrong
**Error**:
invalid character '<' looking for beginning of value
Error: invalid character '<' looking for beginning of value

apart from the above error, what exactly this mountpathMean when importing?

**Comment by Yasinmohammed007** [comment]
@gramosg @vanveele @jonasvinther  Can you please help me out here.

**Comment by gramosg** [comment]
@Yasinmohammed007 Maybe not related to your error but the `address` argument should not include the path to the secret, just the host (in your case, `http://207.254.25.36:8000`).

Also, Vault 0.10.4 is almost 4 years old. You should upgrade to one of the latest versions just in case.

**Comment by jonasvinther** [comment]
Hi @Yasinmohammed007 
I agree with @gramosg. That Vault version is really old, and I have never tested Medusa on such a old version of Vault. 
Also I can see that kv2 was released in version 0.10. So do you know if you are using kv1 or kv2. If you are using kv1 yo need to specify that using the `--engine-type` parameter.

I hope that this brings you somewhere otherwise let me know. And please upgrade your Vault instance. Vault is where you store your secrets, you want it to be secure and not full of potential risks :)
